### ISSUE TITLE
怎么替换我们源码中已有的pods库

### ISSUE THREAD

**Issue by diaojunxian** [bay2/CarthagePods#1]
您好，我看了您的文章翻到了这个开源方案，我想请教你，如何将我们现有代码中pods库替换成你的工具使用呢？我只是一个CI人员，大部分的iOS工程的配置还是看的不是很懂，我是想在拉取到源码后，直接替换将一些pod库打成二进制文件链接到打包过程中，研究了很多文档，都是讲先打成framework，可是没有具体交代打成framework后，如何无缝的插入源代码中，而不能更改什么import方式等。

不知道你的方案能否实现？

**Comment by bay2** [comment]
我这个方案是通过Carthage 自动把 Pod的自动编译成framework，但是你在使用 framework 时，代码应用头文件都必须使用 import <xxxx/xxx.h>这一步你还是必须手动修改

**Comment by diaojunxian** [comment]
@bay2 还想请教你，如果没有支持carthage的库，如何变成framework呢？xcodebuild如何做？你有过实践吗？pod package xxx，好像并不行？

**Comment by bay2** [comment]
如果没有支持carthage的库，如何变成framework呢？
   -- 假如你的库对第三方有依赖，那你是需要使用carthage来管理这些库的
xcodebuild如何做？
  -- 就是编译你项目的framework target
cocoapods-packager
  -- 你可以看一下 [这个](http://www.cnblogs.com/brycezhang/p/4117180.html)
